/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fidness_GUI;

import com.mycompany.fidness_kristel_esquivel.Usuario;
import com.mycompany.fidness_kristel_esquivel.navegacionVentanas;
import javax.swing.JOptionPane;

/**
 *
 * @author krist
 */
public class MenuPrincipalEmpleado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalEmpleado.class.getName());

    /**
     * Creates new form MenuPrincipalEmpleado
     */
    public MenuPrincipalEmpleado() {
        initComponents();
        if (Usuario.idUsuarioActual != null && 
        !Usuario.idUsuarioActual.isEmpty()) {
        idEMPLEADOLABEL.setText("ID: " + Usuario.idUsuarioActual);
    }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idEMPLEADOLABEL = new javax.swing.JLabel();
        ConsultarEjercicios = new javax.swing.JButton();
        ConsultarMaquinas = new javax.swing.JButton();
        registrarMaquinas = new javax.swing.JButton();
        registrarEjercicios = new javax.swing.JButton();
        verUsuariosRegistrados = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menú Principal");

        idEMPLEADOLABEL.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        idEMPLEADOLABEL.setForeground(new java.awt.Color(255, 255, 0));
        idEMPLEADOLABEL.setText("ID Empleado");

        ConsultarEjercicios.setBackground(new java.awt.Color(204, 204, 204));
        ConsultarEjercicios.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        ConsultarEjercicios.setText("Consultar Ejercicios");
        ConsultarEjercicios.addActionListener(this::ConsultarEjerciciosActionPerformed);

        ConsultarMaquinas.setBackground(new java.awt.Color(204, 204, 204));
        ConsultarMaquinas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        ConsultarMaquinas.setText("Consultar Máquinas");
        ConsultarMaquinas.addActionListener(this::ConsultarMaquinasActionPerformed);

        registrarMaquinas.setBackground(new java.awt.Color(204, 204, 204));
        registrarMaquinas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        registrarMaquinas.setText("Registrar Máquinas");
        registrarMaquinas.addActionListener(this::registrarMaquinasActionPerformed);

        registrarEjercicios.setBackground(new java.awt.Color(204, 204, 204));
        registrarEjercicios.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        registrarEjercicios.setText("Registrar Ejercicios");
        registrarEjercicios.addActionListener(this::registrarEjerciciosActionPerformed);

        verUsuariosRegistrados.setBackground(new java.awt.Color(204, 204, 204));
        verUsuariosRegistrados.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        verUsuariosRegistrados.setText("Usuarios Registrados");
        verUsuariosRegistrados.addActionListener(this::verUsuariosRegistradosActionPerformed);

        cerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        cerrarSesion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(this::cerrarSesionActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idEMPLEADOLABEL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConsultarMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConsultarEjercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registrarMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registrarEjercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verUsuariosRegistrados)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(cerrarSesion)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idEMPLEADOLABEL)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ConsultarEjercicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConsultarMaquinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarMaquinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarEjercicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verUsuariosRegistrados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(cerrarSesion)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarEjerciciosActionPerformed
        JOptionPane.showMessageDialog(this, "EN DESARROLLO");
    }//GEN-LAST:event_ConsultarEjerciciosActionPerformed

    private void ConsultarMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarMaquinasActionPerformed
         JOptionPane.showMessageDialog(this, "EN DESARROLLO");
    }//GEN-LAST:event_ConsultarMaquinasActionPerformed

    private void registrarMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMaquinasActionPerformed
         JOptionPane.showMessageDialog(this, "EN DESARROLLO");
    }//GEN-LAST:event_registrarMaquinasActionPerformed

    private void registrarEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEjerciciosActionPerformed
         JOptionPane.showMessageDialog(this, "EN DESARROLLO");
    }//GEN-LAST:event_registrarEjerciciosActionPerformed

    private void verUsuariosRegistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verUsuariosRegistradosActionPerformed
         JOptionPane.showMessageDialog(this, "EN DESARROLLO");
    }//GEN-LAST:event_verUsuariosRegistradosActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        
        navegacionVentanas.cerrarSesion(this);
        this.dispose();
    }//GEN-LAST:event_cerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalEmpleado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarEjercicios;
    private javax.swing.JButton ConsultarMaquinas;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JLabel idEMPLEADOLABEL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrarEjercicios;
    private javax.swing.JButton registrarMaquinas;
    private javax.swing.JButton verUsuariosRegistrados;
    // End of variables declaration//GEN-END:variables
}
